# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-06-09T11:46:09Z"
  labels:
    app: testpod
  name: testpod
spec:
  containers:
    - args:
        - ./sandbox/run.sh
      env:
        - name: HOSTNAME
          value: "{{=env.DOMAIN}}"
        - name: GRIST_SESSION_SECRET
          value: "{{=env.GRIST_SESSION_SECRET}}"
        - name: GRIST_SANDBOX_FLAVOR
          value: gvisor
        - name: APP_HOME_URL
          value: "https://{{=env.DOMAIN}}"
        - name: GRIST_SINGLE_ORG
          value: team
        - name: COOKIE_MAX_AGE
          value: "31536000"
        - name: GRIST_HIDE_UI_ELEMENTS
          value: "billing,multiSite"
        - name: GRIST_PAGE_TITLE_SUFFIX
          value: "_blank"
        - name: GRIST_TELEMETRY_LEVEL
          value: "off"
        - name: APP_STATIC_INCLUDE_CUSTOM_CSS
          value: "true"
        - name: GRIST_WIDGET_LIST_URL
          value: "https://{{=env.DOMAIN}}/widgets/manifest.json"
      image: docker.io/gristlabs/grist:latest
      name: grist
      ports:
        - containerPort: 8484
          hostPort: 33667
      tty: true
      volumeMounts:
        - mountPath: /persist
          name: hosting-grist-data-host-0
        - mountPath: /grist/static/custom.css
          name: hosting-grist-css-host-0
          readOnly: true
        - mountPath: /grist/static/widgets
          name: hosting-grist-widgets-host-0
          readOnly: true
  hostname: "{{=env.DOMAIN}}"
  volumes:
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/data"
        type: Directory
      name: hosting-grist-data-host-0
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/custom.css"
        type: File
      name: hosting-grist-css-host-0
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/widgets"
        type: Directory
      name: hosting-grist-widgets-host-0
