# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    hosting/podgrist-grist: services
  creationTimestamp: "2024-06-15T08:34:34Z"
  labels:
    app: podgrist
  name: podgrist
spec:
  containers:
    - args:
        - ./sandbox/run.sh
      env:
        - name: GRIST_OIDC_SP_HOST
          value: https://grist.dev.hemphill.family
        - name: HOSTNAME
          value: grist.dev.hemphill.family
        - name: COOKIE_MAX_AGE
          value: "31536000"
        - name: GRIST_OIDC_IDP_CLIENT_ID
          value: 0bcae16c-2ba6-4cc8-b557-3c7df1cc5e64
        - name: GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED
          value: "1"
        - name: GRIST_HIDE_UI_ELEMENTS
          value: billing
        - name: GRIST_FORCE_LOGIN
          value: "true"
        - name: GRIST_OIDC_IDP_ISSUER
          value: https://git.hemphill.family/.well-known/openid-configuration
        - name: GRIST_OIDC_IDP_CLIENT_SECRET
          value: gto_okwraizq3iowjam3ipk2rhjy3ycksemfe3g7yx52fwsf5ea46oua
        - name: GRIST_OIDC_IDP_SCOPES
          value: openid profile email read:user
        - name: GRIST_TELEMETRY_LEVEL
          value: "off"
        - name: GRIST_SANDBOX_FLAVOR
          value: gvisor
        - name: GRIST_WIDGET_LIST_URL
          value: http://grist.dev.hemphill.family:8484/v/unknown/widgets/manifest.json
        - name: GRIST_DEFAULT_EMAIL
          value: j1.robofan@gmail.com
        - name: GRIST_SESSION_SECRET
          value: qN3vBvWftZUxuUfX97ep4ByDuJpTYtJARrqc7sjK
        - name: DEBUG
          value: "1"
        - name: GRIST_OIDC_IDP_SKIP_END_SESSION_ENDPOINT
          value: "true"
        - name: GRIST_PAGE_TITLE_SUFFIX
          value: _blank
        - name: APP_HOME_URL
          value: https://grist.dev.hemphill.family
      image: docker.io/gristlabs/grist:latest
      name: podgrist-grist
      ports:
        - containerPort: 8484
          hostPort: 33670
      tty: true
      volumeMounts:
        - mountPath: /persist
          name: home-josh-hosting-services-grist-data-host-0
        - mountPath: /grist/static/custom.css
          name: home-josh-hosting-services-grist-custom.css-host-1
          readOnly: true
        - mountPath: /grist/static/widgets
          name: home-josh-hosting-services-grist-widgets-host-2
          readOnly: true
  hostname: grist.dev.hemphill.family
  restartPolicy: Always
  volumes:
    - hostPath:
        path: /home/josh/hosting/services/grist/data
        type: Directory
      name: home-josh-hosting-services-grist-data-host-0
    - hostPath:
        path: /home/josh/hosting/services/grist/custom.css
        type: File
      name: home-josh-hosting-services-grist-custom.css-host-1
    - hostPath:
        path: /home/josh/hosting/services/grist/widgets
        type: Directory
      name: home-josh-hosting-services-grist-widgets-host-2
