# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2

# NOTE: The namespace sharing for a pod has been modified by the user and is not the same as the
# default settings for kubernetes. This can lead to unexpected behavior when running the generated
# kube yaml in a kubernetes cluster.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-06-10T05:34:32Z"
  labels:
    app: pod-gitea
  name: pod-gitea
  annotations:
    io.podman.annotations.userns: keep-id
spec:
  containers:
    - env:
        - name: GITEA__server__DOMAIN
          value: "{{=env.DOMAIN}}"
        - name: GITEA__server__ROOT_URL
          value: "https://{{=env.DOMAIN}}"
      image: gitea/gitea:latest-rootless
      name: gitea
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      ports:
        - containerPort: 3000
          hostPort: 3000
      volumeMounts:
        - mountPath: /etc/gitea
          name: gitea-config-host-0
        - mountPath: /var/lib/gitea
          name: gitea-data-host-2
        - mountPath: /etc/localtime
          name: gitea-localtime-host-0
          readOnly: true
        - mountPath: /etc/timezone
          name: gitea-timezone-host-3
          readOnly: true
  volumes:
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/config"
        type: Directory
      name: gitea-config-host-0
    - hostPath:
        path: "{{=env.SERVICE_DIR}}/data"
        type: Directory
      name: gitea-data-host-2
    - hostPath:
        path: "/etc/localtime"
        type: File
      name: gitea-localtime-host-0
    - hostPath:
        path: "/etc/timezone"
        type: File
      name: gitea-timezone-host-3
